<template>
  <div class="  ">
    <div class="overflow-hidden">
    <Header class="absolute top-0  z-0 h-20"></Header>
    
    
      <div class="h-32 w-full">
      
      </div>
   
  
    <div :class="card ? 'block' : 'hidden'"> 
      <section class=" container my-5 mx-auto "> 
      <h1 class="family text-5xl text-center">{{cardName}} Scratch Card</h1>
      <p class="text-2xl font-semibold text-center ">Buy {{cardName}} Direct Access Card Here</p>
      </section>
      <section class="container mx-auto">
      <div class="flex flex-col items-center gap-5  ">

        <div class=" w-1/2"><img :src="waecImg" alt="" ></div>
            <PrimaryBtn @click="Startpayment" class="ronded duration-500 rounded-xl hover:bg-secondary">Proceed to payment</PrimaryBtn>
            <div class="w-  flex flex-col gap-3">
            <div class="flex flex-col gap-5">
                <div :class="waec ? 'block' : 'hidden'"><h1 class="text-primary  font-bold text-xl"   >Buy {{cardName}} Online</h1>
                <p class="font-semibold text-sm ">The West {{full_name}} produced the <span>{{cardName}}</span> Scratch Card. It comprises of a Pin and Serial Number that may be used to check the results of applicants who took the May/June (internal or school applicants) or November/December (all applicants) <span>{{ cardName }}</span> Exams (GCE or Private Candidates).</p>
              </div>

                <div :class="nabteb ? 'block' : 'hidden'"><h1 class="text-primary  font-bold text-sm"   >Buy {{cardName}} Online</h1>
                <p>The West {{full_name}} produced the <span>{{cardName}}</span> Scratch Card. It comprises of a Pin and Serial Number that may be used to check the results of applicants who took the May/June (internal or school applicants) or November/December (all applicants) <span>{{ cardName }}</span> Exams (GCE or Private Candidates).</p>
              </div>

                <div :class="neco ? 'block' : 'hidden'"><h1 class="text-primary  font-bold text-xl"   >Buy {{cardName}} Online</h1>
                <p  class="text-sm font-semibold">
                The Neco Scratch Card, also known as the Neco Result Checker Token or Neco Token, is the same thing as the Neco Token. For students who took part in NECO exams (both School Exams and External GCE), the National Examinations Council (NECO) has created a special 12-digit code called Our Neco Result Checker Token that they can use to view their results online.Our Neco Result Checker Token, a one-of-a-kind 12-digit number generated by the National Examinations Council (NECO), is given to students who took NECO examinations (both School Exams and External GCE) in order to enable them to view their results online. </p>
              </div>
                
                <div>
                    <h1 class="text-xl text-primary font-bold mb-2">How to Buy {{cardName}} card </h1>
                    <ul class=" tracking-normal text-sm font-semibold list-decimal">
                
                <li> Visit www.abaniseedu.com</li>
                <li> Click on BUY NOW below the <span> </span>Image.</li>
                <li>Proceed to Payment on the Checkout Page</li>
                <li>Make Payment using our secure payment channels, PAYSTACK or FLUTTERWAVE </li>
                <li>Your Card is instantly displayed on your screen and delivered to your email for future reference.</li>
                </ul>
                </div>

            </div> 
                

              <div class="flex flex-col gap-5">
              
                <div >
                    <h1 class="text-xl mb-2 font-bold text-primary">How to Check {{cardName}}Results Online </h1>
                    <ul class="text-sm font-semibold tracking-normal list-decimal">
                  <li class="text-sm font-semibold "> <span class="flex gap-1"> Visit the Official Website, <a href="https://www.waecdirect.org" target="_black" :class="waec ? 'block' : 'hidden'" class="text-[red]" >https://www.waecdirect.org</a>
                    <a href="https://results.neco.gov.ng/" target="_black" class="text-[red]" :class="neco ? 'block' : 'hidden'"  >https://results.neco.gov.ng</a>
                      <a href="https://eworld.nabteb.gov.ng/" target="_black" :class="nabteb ? 'block' : 'hidden'" class="text-[red]" >www.eworld.nabteb.gov.ng</a></span>
                  </li> 
                <li class="text-sm font-semibold"> Select your Exam Year and Exam Type</li>
                <li>Enter your Exam Number <span class="text-sm font-semibold" :class="wlabel ? 'block' : 'hidden'" >  a combination of your Center Number and Seat Number).</span></li>
                <li class="text-sm font-semibold"> Input the Card details Pin  <span :class="wlabel ? 'block' : 'hidden'" >and Serial Number</span> you bought from www.abaniseede.com</li>
                <li class="text-sm font-semibold">Click on Submit.</li>
                <li>Congratulations.  Your Result is displayed on a new window.  You can save or print for reference purpose..</li>
                </ul>
                </div>
              </div>
              <p class="text-xl">NOW CLICK ON THE 'PROCEED TO PAYMENT' button below to get your {{cardName}} Scratch Card.</p>

            <div class="w-full flex items-center"> <PrimaryBtn class="ronded duration-500 w-fit  text-center
              rounded-xl hover:bg-secondary" @click="Startpayment">Proceed to payment</PrimaryBtn></div>
            </div>
        <div> 
      </div>


      </div>
      </section>
    </div>



   <div :class="vcard ? 'block' : 'hidden'"> 
    <section class=" container my-5 mx-auto "> 
    <h1 class="family text-4xl text-center">Buy  {{cardName}} Pin Online</h1>
    <p class="text-2xl font-semibold text-center ">Buy GCE{{cardName}} Pin Direct Access  Here</p>
    </section>

    <section class="container mx-auto">
      <div class="flex flex-col items-center gap-5  ">

      <div class=" w-1/2"><img :src="waecImg" alt="" ></div>
          <PrimaryBtn @click="Startpayment" class="ronded duration-500 rounded-xl hover:bg-secondary">Proceed to payment</PrimaryBtn>
          <div class="w-2/3  flex flex-col gap-3">
          <div class="flex flex-col gap-5">
              <div :class="vcard ? 'block' : 'hidden'"><h1 class="text-primary  font-bold text-xl"   >Buy {{cardName}} Online</h1>
              <p class="text-sm font-semibold ">
               {{descrption}}
              </p>
            </div>
              
              <div>
                  <h1 class="text-xl text-primary font-bold mb-2">How to Buy {{cardName}} card </h1>
                  <ul class=" tracking-normal  text-sm font-semibold list-decimal">
              <li> Visit www.abaniseedu.com</li>
              <li> Click on BUY NOW below the <span> </span>Image.</li>
              <li>Proceed to Payment on the Checkout Page</li>
              <li>Make Payment using our secure payment channels, PAYSTACK or FLUTTERWAVE </li>
              <li>Your Card is instantly displayed on your screen and delivered to your email for future reference.</li>
              </ul>
              </div>

          </div> 
              

            <div class="flex flex-col gap-5">
            
              <div :class="Nabtebre  ? 'hidden' : 'block'">
                  <h1 class="text-xl font-semibold mb-2 font-bold text-primary" >How to Register for {{cardName}}  Online </h1>
                  <ul class="tracking-normal  text-sm font-semibold list-decimal">
                    <li>Visit <a class="text-red" href=" https://novdec.nabtebnigeria.org">https://novdec.nabtebnigeria.org</a> </li>
                   <li>and enter the PIN and Serial No</li>
                   <li>and follow the registration steps.</li>
                  </ul>
                 
              </div>

              <div :class="gceWaec? 'hidden' : 'block'">               
                   <h1 class="text-xl font-semibold mb-2 font-bold text-primary">How to Register for{{cardName}}  Online </h1>
                  <p  class="text-[14px] font-semibold ">firstly All you have to do is download the software from the WAEC website and purchase a registration PIN from our website, abaniseedu.com. The WAEC Biometric Fingerprint Registration software is a collection of applications that candidates must use in order to successfully register their fingerprints for the Nov/Dec WASSCE registration exercise. </p>
                  <p class="font-semibold text-[15px]">Software and processes you need for registration</p>
                 
                   <ul class=" font-semibold text-sm tracking-normal list-decimal">
                    <li>Microsoft .Net Framework 4.5 (if not already installed on your system)</li>
                    <li>Crossmatch UareU RTE</li>
                    <li>WAEC Biometric Client</li>
                    <li>Depending on your hardware architecture, you will need to download       either the x86 or x64 versions of the RTE.</li>
                    <li class=" "> <span class="flex gap-1"> Visit the Official Website, <a href="https://www.waecdirect.org" target="_black" :class="waec ? 'block' : 'hidden'" class="text-[red]" >https://www.waecdirect.org</a>
                       </span>
                    </li> 
                    <li> click on the "WASSCE (For Private Candidates)" image </li>
                    <li>Enter your Exam Numberclick on the "WASSCE (For Private Candidates)" image</li>
                    <li>Then select the WASSCE exam type, either First Series - January/February WAEC Registration or First Series - January/February WAEC Registration</li>
                    <li>WAEC Online Registration for WASSCE for Private Candidates - First Series (2023) is currently ongoing</li>
                    <li>The WASSCE for private candidates 2023 - FIRST SERIES WAEC REGISTRATION CLOSES ON: 31/08/2023</li>
                    <li>WAEC Online Registration 2023 - First Series for private candidate registration period may be extended</li>
                  </ul>
              </div>
            </div>
            <p class="text-xl">NOW CLICK ON THE 'PROCEED TO PAYMENT'</p>

          <div class="w-full flex items-center"> <PrimaryBtn class="ronded duration-500 w-fit  text-center rounded-xl hover:bg-secondary" @click="Startpayment">Proceed to payment</PrimaryBtn></div>
          </div>
        <div> 
      </div>


      </div>
    </section>
    </div>


    
   <div :class="nysecard ? 'block' : 'hidden'"> 
    <section class=" container my-5 mx-auto "> 
    <h1 class="family text-3xl text-center">Buy  {{cardName}}</h1>
    <p class="text-2xl font-semibold text-center ">Buy {{cardName}} Direct Access  Here</p>
    </section>

     <section class="container mx-auto">
    <div class="flex flex-col items-center gap-5  ">

      <div class=" w-1/2"><img :src="waecImg" alt="" ></div>
          <PrimaryBtn @click="Startpayment" class="ronded duration-500 rounded-xl hover:bg-secondary">Proceed to payment</PrimaryBtn>
          <div class="w-2/3  flex flex-col gap-3">
          <div class="flex flex-col gap-5">
              <div><h1 class="text-primary text-xl font-semibold "   >Buy {{cardName}} Online</h1>
              <p class="font-semibold text-sm">It is no longer news that many graduates and PCMs face issues such as incorrectly entering their Date of Birth on their NYSC Dashboards during mobilization. This frequently causes them to be perplexed as to what to do next. If this is you, don't worry. It is not your fault that the incorrect Date of Birth was recorded for you. I understand that you simply need to find a way to correct this incorrect Date of Birth so that it does not appear on your NYSC Certificate. I have some good news for you. You only need a Waec Verification Pin. You can correct this incorrect date of birth with a Waec Verification Pin. You simply need to purchase a NYSC Waec Verification Pin.
                <br>
              What Is the Function of a Waec Verification Pin?
              The NYSC Waec Verification Pin is a number combination that creates a unique personal identification number (PIN) that is used to verify Waec results as well as the correct NYSC Date of Birth. 
              <br><br>
              If you are confident that the Date of Birth on your Waec O-level result is correct, the next step is to purchase a Waec Verification Pin.</p>
            </div>

            
              
              <div>
                  <h1 class="text-xl text-primary font-bold mb-2">How to Buy  Waec Verification Pin </h1>
                  <ul class=" tracking-normal list-decimal">
              <li> Visit www.abaniseedu.com</li>
              <li> Click on BUY NOW below the <span> </span>Image.</li>
              <li>Proceed to Payment on the Checkout Page</li>
              <li>Make Payment using our secure payment channels, PAYSTACK or FLUTTERWAVE </li>
              <li>Your Card is instantly displayed on your screen and delivered to your email for future reference.</li>
              </ul>
              </div>

          </div> 
              

            <div class="flex flex-col gap-5">
            
              <div >
                  <h1 class="text-xl mb-2 font-bold text-primary">How to Change Your Birthdate on the NYSC Website  </h1>
                  <ul class="text-sm tracking-normal list-decimal">
                <li class=" ">  Login in to your NYSC Dashboard and Scroll down</li> 
              <li>Click on Change DOB WAEC at the bottom of the page.</li>
              <li>Enter the Pin you bought from abaniseede Pins </li>
              <li> Submit </li>
              <li>Congratulations.  You are done with the process.</li>
              </ul>
              </div>
            </div>
            <p>note!!!: Congratulations.  You are done with the process.</p>
            <p class="text-xl">NOW CLICK ON THE 'PROCEED TO PAYMENT' button below to get your Waec Scratch Card.</p>

          <div class="w-full flex items-center"> <PrimaryBtn class="ronded duration-500 w-fit  text-center
            rounded-xl hover:bg-secondary" @click="Startpayment">Proceed to payment</PrimaryBtn></div>
          </div>
      <div> 
    </div>


    </div>
    </section>
    </div>
    <div class="w-full  fixed top-0 z-20  bg-black bg-opacity-50 items-center flex justify-center h-full px-6 md:px-0 lg:px-10" :class="paymentpage ? 'block' : 'hidden'">
    <div class="ul overflow-scroll mx-auto mt-20  bg-white py-5 h-screen px-10 lg:w-1/3 md:w-1/2 w-fu ">
          <div class="flex mb-5 justify-between">
            <p class=" font-bold">check point</p>
           <div @click="hiddenpage()"> <img src="@/assets/image/cancel.svg" class="w-8"/></div>
          </div>

           <div class=" border drop-shadow-2xl py-5 px-5   rounded-xl bg-white bg-gray-100">
          <form action="" class=" ">
            <div class="flex flex-col justify-center mb-10 items-center">
            <h1 class="text-primary font-bold text-xl ">Scratch card</h1>
            <h1 class="text-2xl font-normal text-secondary ">{{cardName}} Scratch Card</h1>
            <h1 class="text2xl text-black  ">{{this.form.semiprice}}</h1>
            </div>
            <Input label="Enter Quantity" type="number"    @click="calculate()" placeholder="Enter Quantity" :error="false" v-model:inputValue="form.quantity" inputValue="1"  :min="numm"></Input>
           
           <Input label="Charges" type="text" placeholder="Enter your email address" :error="false" inputValue="100" :disabled=disabled ></Input>
        <Input label="Total"   type="Number" :min="numm" :disabled=disabled  :error="false" v-model:inputValue="form.total"
          class="mt-4 "></Input>
              
          
     
          <p class="text-sm text-center mt-5 ">Make payment with</p> 
          <div class="w-full flex justify-center">
            <PrimaryBtn @click="calculate()" class="rounded-xl text-xl flex gap-3 mt-5 w-fit">  Paystack<img src="@/assets/image/paystack.png" alt="" class="w-5 "></PrimaryBtn>
           
            
          </div> <div class="h-10 w-full"></div>
        </form>

        </div>
       
    </div>
    </div>
   
    </div>
  </div>
  <Footer></Footer>
</template>
  <script>

  import waec from '../assets/image/waec.png'
  import neco from '../assets/image/neco12.jpg'
  import nabteb from '../assets/image/nee.jpg'
  import nabtebgce from '../assets/image/pinnabteb.jpg'
  import vwaec from '../assets/image/waecver.jpg'
  import gcewaec from  '../assets/image/gce.jpg'
   const locationName = window.location.href
 const splitloc = locationName.split('/');
console.log(splitloc);

export default {
   
 data(){
    return {
      nysecard:'',
      descrption:'',
     disabled:true,
      numm:Number(1),
      vcard:'',
      wlabel:'',
      nabteb:'',
      waec:'',
      neco:'',
      waecImg:'waec',
      cardlink:'',
      cardName : '',
      full_name:'',
      website: '',
      paymentpage: false,
      form: {
        semiprice:'',
        quantity:  1,
        total:  '', 
        price:Number,
        email:'',
       
      },
     
    }
   
    
  },
 
  methods:{
      Startpayment(){
       this.paymentpage = !this.paymentpage
      },
   
    
   hiddenpage(){
    this.paymentpage = !this.paymentpage
    },
    paymentPage(){
     this.paymentpage = !this.paymentpage
     
    },
    calculate(){
      this.form.total = this.form.quantity * this.form.price
      console.log(this.form.total)
    },
   
  },

 created(){
  this.form.email  
  console.log(this.form.email)
  if (splitloc[4]== 1 ) {
    this.form.semiprice = Number(3200)
    this.form.price = this.form.semiprice
    this.cardName='Waec',
    this.waecImg=waec,
     this.card=true
    this.wlabel=true

    this.waec=true
    this.full_name='Western Afriacan Examination Councell'
  } else {
      if (splitloc[4]== 2) {
      this.form.semiprice = Number(1000)
      this.form.price = this.form.semiprice
      this.cardName='Neco',
      this.waecImg=waec,
      this.card=true
      this.full_name='National Examination cancil'
      this.neco = !this.neco
      this.waecImg=neco
      } else {
       if (splitloc[4]== 3) {
        this.form.semiprice = Number(1500)
        this.form.price = this.form.semiprice
        this.cardName='Nabteb',
        this.websiteLink='www.eworld.nabteb.gov.ng',
        this.full_name='National Businesss technology cancil'
        this.nabteb = !this.nabteb
        this.waecImg=nabteb
        this.card=true
       } else {
        if (splitloc[4]== 4) {
          this.form.semiprice = Number(19000)
        this.form.price = this.form.semiprice
          this.vcard=true
          this.card=false
          this.Nabtebre =true
          this.descrption=' This card is a product of The West African Examinations Council. It is used for the registration of candidates for GCE Private examinations. A Pin can only be used only once for a candidate.'
          this.cardName='GCEWaec'
         this.waecImg=gcewaec
        } else {
          if (splitloc[4]== 5) {
          this.form.semiprice = Number(19000)
            this.vcard=true
           this.card=false
           this.gceWaec = true
           this.Nabtebre= false
            this.waecImg= nabtebgce
            this.cardName='Nabteb'
            this.descrption='NABTEB GCE O LEVEL card is a product of National Business and Technical Examinations Board. It is used to register candidates for NABTEB Private Examination.'
          } else {
            if (splitloc[4]== 6) {
               this.nysecard= true
                this.vcard= false
                 this.card= false
                 this.cardName= 'Waec Verification Pin'
                 this.waecImg = vwaec
            } else {
              
            }
               
          }
        }
       } 
      }
  }
 },
 
components:{
  
}    

}
</script>




<style>
.scroll-hide ul::-webkit-scrollbar { 
  width: 0 !important;
  display: none; 
}

.ul{
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}

.ul::-webkit-scrollbar {
    display: none;
}

 .blur{
    
   

    filter: blur(8px);
  -webkit-filter: blur(8px);
    }
</style>